[package]
name = "Liquidswapv05"
version = "0.5.0"
upgrade_policy = "immutable"

[addresses]
liquidswap_v05 = "0xd5367fdfa219cb0a108c7751cdbfbb02bfcb71ea932c33007b10a05ae5502500"

# Admins
dao_admin = "0x12bb1da47e9b7e7644bb881eff91d730b001aed21e7e5d49e8ae616a466575d7"
emergency_admin = "0x12bb1da47e9b7e7644bb881eff91d730b001aed21e7e5d49e8ae616a466575d7"
fee_admin = "0x12bb1da47e9b7e7644bb881eff91d730b001aed21e7e5d49e8ae616a466575d7"

# Resource accounts: should be the same as @liquidswap_lp in lp_coin
liquidswap_pool_account = "0x3851f155e7fc5ec98ce9dbcaf04b2cb0521c562463bd128f9d1331b38c497cf3"
liquidswap_emergency_account = "0x6332e12a412f477e15b01cd2c102c712b9c24eeab75b4f3d44f7cd7aaec3174a"

# Addresses for tests.
test_coin_admin = "0x11"
test_helpers = "0x12"

test_lp_owner = "0x12"
test_pool_addr = "0x2540b6f8a87ac1cff2de9f5f742854b448cd4521e96f840eda05e63e4e944ed6"

[dependencies.LiquidswapLPv05]
local = "./liquidswap_lp/"

[dependencies.LiquidswapInitv05]
local = "./liquidswap_init/"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.UQ64x64]
git = "https://github.com/pontem-network/UQ64x64.git"
rev = "movement-mainnet"