[package]
name = "Liquidswapv05"
version = "0.5.0"
upgrade_policy = "immutable"

[addresses]
liquidswap_v05 = "0x45ef7a3a1221e7c10d190a550aa30fa5bc3208ed06ee3661ec0afa3d8b418580"

# Admins
dao_admin = "0xb247ddeee87e848315caf9a33b8e4c71ac53db888cb88143d62d2370cca0ead2"
emergency_admin = "0xb247ddeee87e848315caf9a33b8e4c71ac53db888cb88143d62d2370cca0ead2"
fee_admin = "0xb247ddeee87e848315caf9a33b8e4c71ac53db888cb88143d62d2370cca0ead2"

# Resource accounts: should be the same as @liquidswap_lp in lp_coin
liquidswap_pool_account = "0x9cc3c27b8d398ab6fc82cbc9dc6b43bb9164f72da465631628163822662a8580"
liquidswap_emergency_account = "0xd542eed06b583e5c8b6a8ded0451669fc89d69ca89b9d0f2512f16fb06c6acd7"

# Addresses for tests.
test_coin_admin = "0x11"
test_helpers = "0x12"

test_lp_owner = "0x12"
test_pool_addr = "0x2540b6f8a87ac1cff2de9f5f742854b448cd4521e96f840eda05e63e4e944ed6"

[dependencies.LiquidswapLPv05]
local = "./liquidswap_lp/"

[dependencies.LiquidswapInitv05]
local = "./liquidswap_init/"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.UQ64x64]
git = "https://github.com/pontem-network/UQ64x64.git"
rev = "v0.3.9"
