[package]
name = 'LiquidswapLPv05'
version = '1.0.0'
upgrade_policy = "immutable"

[addresses]
liquidswap_lp = "0x3851f155e7fc5ec98ce9dbcaf04b2cb0521c562463bd128f9d1331b38c497cf3"

[dev-dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/move-stdlib"
