[package]
name = 'LiquidswapLPv05'
version = '1.0.0'
upgrade_policy = "immutable"

[addresses]
liquidswap_lp = "0xef76ab9e5e26b867a7c09c631ad45d11ffff7eba835cd0cde0cf33f9bbb9b59"

[dev-dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/move-stdlib"
