name: Tests
on:
  pull_request:
  push:
    branches:
      - main
      - master
      - releases-v*
    tags:
      - v*

jobs:
  tests:
    name: Test
    # todo: fix ubuntu latest:
    # todo: aptos: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
    # runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Aptos
        uses: pontem-network/get-aptos@main
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          prover: true

      - name: Build
        run: aptos move compile

      - name: Test Liquidswap
        run: aptos move test