[package]
name = 'LiquidswapInitv05'
version = '1.0.0'
upgrade_policy = "immutable"

[addresses]
liquidswap_v05 = "0xd5367fdfa219cb0a108c7751cdbfbb02bfcb71ea932c33007b10a05ae5502500"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
