[package]
name = 'LiquidswapInitv05'
version = '1.0.0'
upgrade_policy = "immutable"

[addresses]
liquidswap_v05 = "0x4820b22c0bd3049a2bc17c7b00fd94fd42fb97b39be9195fcab9ef02a5ff0323"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
